import json
import requests
import re
from config.settings import settings

NVIDIA_API_KEY = settings.NVIDIA_API_KEY
NVIDIA_API_URL = settings.NVIDIA_API_URL

# Global cache for the current session to prevent double API calls by Streamlit
_llm_cache = {}

def call_llm(description):
    headers = {
        "Authorization": f"Bearer {NVIDIA_API_KEY}",
        "Content-Type": "application/json"
    }
    
    prompt = f"""
    Analyze the following disaster response help request (which might come from a group chat or direct input).
    Extract the following information and output ONLY a valid JSON object. No markdown, no other text.

    1. "thought_process": A chain-of-thought string where you silently think step-by-step about what the user is asking, identifying numbers, detecting skills required, and determining the classification.
    2. "category": The best fitting category from: ["Health", "Relief", "Logistics", "Safety", "Mental Health", "Environment", "Admin", "Education", "General"].
    3. "urgency": Priority level from: ["Critical", "High", "Medium", "Low"].
    4. "people_count": Integer representing the number of people affected. Look closely for numbers like '23 people', 'a dozen', 'five families'. If not specified or vague, return null.
    5. "understood_reasoning": A detailed explanation (1-2 sentences) of what you understood from the request, explicitly mentioning the keywords or context used to determine the category, urgency, and scale. Act as the AI coordinator.

    Help Request:
    "{description}"

    JSON:
    """
    
    payload = {
        "model": "meta/llama-3.1-8b-instruct",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.1,
        "max_tokens": 512
    }
    
    try:
        response = requests.post(NVIDIA_API_URL, headers=headers, json=payload, timeout=12)
        content = response.json()['choices'][0]['message']['content']
        # Clean potential markdown wrapping
        content = content.replace("```json", "").replace("```", "").strip()
        return json.loads(content)
    except Exception as e:
        print("LLM Error:", e)
        return None

def get_cached_llm(description):
    if not description or len(description.strip()) < 3:
        return None
        
    if description not in _llm_cache:
        _llm_cache[description] = call_llm(description)
    return _llm_cache[description]

def classify_task(description):
    """
    Categorizes the task using NVIDIA NIM LLM.
    Returns: (category, initial_urgency)
    """
    res = get_cached_llm(description)
    if res:
        cat = res.get("category", "General")
        if isinstance(cat, list) and len(cat) > 0:
            cat = cat[0] # Fallback to primary category
        elif not isinstance(cat, str):
            cat = str(cat)
            
        return cat, res.get("urgency", "Low")
    return "General", "Low"

def extract_impact_count(description):
    """
    Extracts people count using NVIDIA NIM LLM.
    """
    res = get_cached_llm(description)
    if res and res.get("people_count") is not None:
        try:
            return int(res["people_count"])
        except (ValueError, TypeError):
            pass
    return None

def get_llm_reasoning(description):
    """
    Returns the reasoning string and internal thought process generated by the LLM.
    """
    res = get_cached_llm(description)
    if res:
        summary = res.get("understood_reasoning", "I processed the request with standard AI algorithms.")
        thoughts = res.get("thought_process", "Thinking trace unavailable.")
        return summary, thoughts
    return "I processed the request with my standard algorithms.", "Trace not found."
